export const UPDATE_AGE = "UPDATE_AGE";
export const START_LOADING = "START_LOADING";
export const FINISH_LOADING = "FINISH_LOADING";
export const INCREMENT_AGE_ACTION = "INCREMENT_AGE_ACTION";
export const DECREMENT_AGE_ACTION = "DECREMENT_AGE_ACTION";